/*
Navicat MySQL Data Transfer

Source Server         : Localhost
Source Server Version : 50624
Source Host           : localhost:3306
Source Database       : ubudsatu

Target Server Type    : MYSQL
Target Server Version : 50624
File Encoding         : 65001

Date: 2016-01-28 10:00:19
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `m1000`
-- ----------------------------
DROP TABLE IF EXISTS `m1000`;
CREATE TABLE `m1000` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `kd_menu` varchar(50) NOT NULL,
  `nm_menu` varchar(200) NOT NULL,
  `jval` longtext,
  `note` text,
  `created_by` varchar(100) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `status` smallint(6) DEFAULT '1',
  PRIMARY KEY (`id`,`kd_menu`)
) ENGINE=InnoDB AUTO_INCREMENT=113 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of m1000
-- ----------------------------
INSERT INTO `m1000` VALUES ('1', 'admin', 'admin', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Chating\",\"url\":[\"/widget/chat\"]},\r\n{\"label\":\"<i class=\\\"fa fa-folder-o\\\"></i> User SignUp \",\"url\":[\"/sistem/user\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> User Permission\",\"url\":[\"/admin\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Menu Route\",\"url\":[\"/admin/route\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Menu Fill\",\"url\":[\"/admin/menu\"]},\r\n{\"label\":\"<i class=\\\"fa fa-inbox\\\"></i>  Permission Menu \",\"url\":[\"/admin/permission\"]},\r\n{\"label\":\"<i class=\\\"fa fa-suitcase\\\"></i> Menu Rule<span id=\\\"menu-badge-1\\\" class=\\\"badge badge-purple\\\" style=\\\"float: right\\\"></span>\",\"url\":[\"/admin/rule\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Menu Roles\",\"url\":[\"/admin/role\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> ERP Modul Permission\",\"url\":[\"/system/mdlpermission\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> ERP Modul\",\"url\":[\"/system/modulerp\"]}\r\n]', null, null, null, null, '2015-11-21 13:00:37', '1');
INSERT INTO `m1000` VALUES ('2', 'berita_acara', 'Berita Acara', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site/index\"]}\r\n]', null, null, null, null, '2015-08-29 00:35:56', '1');
INSERT INTO `m1000` VALUES ('20', 'umum_datamaster', 'LG DataMaster', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Dashboard\",\"url\":[\"/dashboard/master-barang\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Chating\",\"url\":[\"/dashboard/master-barang/chat\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Barang Tipe \",\"url\":[\"/master/tipebarang\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Barang Kategori \",\"url\":[\"/master/kategori\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Barang Umum\",\"url\":[\"/master/barangumum\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Barang Produk\",\"url\":[\"/master/barang\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Barang Unit \",\"url\":[\"/master/unitbarang\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Supplier\",\"url\":[\"/master/suplier\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Distributor\",\"url\":[\"/master/distributor\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Customer\",\"url\":[\"/master/customers\"]}\r\n]', null, null, null, null, '2016-01-23 22:28:34', '1');
INSERT INTO `m1000` VALUES ('21', 'umum_adminweb_lg', 'Web Admin ERP PRONT LG', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Dashboard\",\"url\":[\"/dashboard/adminweb-lg\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Chating\",\"url\":[\"/dashboard/adminweb-lg/chat\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> LG Parent\",\"url\":[\"/front/back-parent\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> LG Child \",\"url\":[\"/front/back-child\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> LG Grand Child \",\"url\":[\"/front/back-grandchild\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> LG Posting \",\"url\":[\"/front/back-posting\"]}\r\n]', null, null, null, null, '2016-01-16 20:41:49', '1');
INSERT INTO `m1000` VALUES ('22', 'umum_adminweb_crm', 'Web Admin CRM  PRONT', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Dashboard\",\"url\":[\"/dashboard/adminweb-lg\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Chating\",\"url\":[\"/dashboard/adminweb-lg/chat\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> CRM Parent\",\"url\":[\"/front/back-parent\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> CRM Child \",\"url\":[\"/front/back-child\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> CRM Grand Child \",\"url\":[\"/front/back-grandchild\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> CRM Posting \",\"url\":[\"/front/back-posting\"]}\r\n]', null, null, null, null, '2016-01-16 20:42:39', '1');
INSERT INTO `m1000` VALUES ('30', 'hrd_personalia', 'HRD Personalia', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Dashboard\",\"url\":[\"/dashboard/hrm-personalia\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Chating\",\"url\":[\"/dashboard/hrm-personalia/chat\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Employee Data\",\"url\":[\"/hrd/employe/index\"]},\r\n{\"label\":\"<i class=\\\"fa fa-suitcase\\\"></i> Employee  Arsip<span id=\\\"menu-badge-1\\\" class=\\\"badge badge-purple\\\" style=\\\"float: right\\\"></span>\",\"url\":[\"#\"]}\r\n]', null, null, null, null, '2015-11-21 11:57:49', '1');
INSERT INTO `m1000` VALUES ('31', 'hrd_modul', 'HRD_Modul', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Dashboard\",\"url\":[\"/dashboard/hrm-modul\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Chating\",\"url\":[\"/dashboard/hrm-modul/chat\"]},\r\n{\"label\":\"<i class=\\\"fa fa-send\\\"></i> Visi Misi\",\"url\":[\"/hrd/visi/index\"]},\r\n{\"label\":\"<i class=\\\"fa fa-send\\\"></i> Organization \",\"url\":[\"/hrd/organisasi/index\"]},\r\n{\"label\":\"<i class=\\\"fa fa-send\\\"></i> Modul Jobgrade\",\"url\":[\"/hrd/jobgrademodul\"]},\r\n{\"label\":\"<i class=\\\"fa fa-send\\\"></i> Coorporate\",\"url\":[\"/hrd/corp\"]},\r\n{\"label\":\"<i class=\\\"fa fa-send\\\"></i> Department\",\"url\":[\"/hrd/dept\"]},\r\n{\"label\":\"<i class=\\\"fa fa-send\\\"></i> Department  Sub\",\"url\":[\"/hrd/deptsub\"]},\r\n{\"label\":\"<i class=\\\"fa fa-send\\\"></i> Group Function\",\"url\":[\"/hrd/groupfunction\"]},\r\n{\"label\":\"<i class=\\\"fa fa-send\\\"></i> Group Seqmen\",\"url\":[\"/hrd/groupseqmen\"]},\r\n{\"label\":\"<i class=\\\"fa fa-send\\\"></i> Jobgrade\",\"url\":[\"/hrd/jobgrade\"]}\r\n]', null, null, null, null, '2015-11-21 11:56:18', '1');
INSERT INTO `m1000` VALUES ('40', 'sss_marketing', 'SSS Marketing', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Dashboard\",\"url\":[\"/dashboard/sss-marketing\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Chating\",\"url\":[\"/dashboard/sss-marketing/chat\"]}\r\n]', null, null, null, null, '2016-01-16 20:39:03', '1');
INSERT INTO `m1000` VALUES ('41', 'sss_sales', 'SSS Sales', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Dashboard\",\"url\":[\"/dashboard/sss-sales\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Chating\",\"url\":[\"/dashboard/sss-sales/chat\"]}\r\n]', null, null, null, null, '2016-01-16 20:38:58', '1');
INSERT INTO `m1000` VALUES ('42', 'sss_purchasing', 'SSS Purchasing', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Dashboard\",\"url\":[\"/dashboard/sss-purchasing\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Chating\",\"url\":[\"/dashboard/sss-purchasing/chat\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Product\",\"url\":[\"/sss/prodak\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Tenant\",\"url\":[\"/sss/tenant\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Consumer\",\"url\":[\"/sss/konsumen\"]}\r\n]', null, null, null, null, '2016-01-16 20:38:50', '1');
INSERT INTO `m1000` VALUES ('43', 'sss_warehouse', 'SSS Warehouse', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Dashboard\",\"url\":[\"/dashboard/sss-warehouse\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Chating\",\"url\":[\"/dashboard/sss-warehouse/chat\"]}\r\n]', null, null, null, null, '2016-01-16 20:38:44', '1');
INSERT INTO `m1000` VALUES ('45', 'sss_berita_acara', 'Berita Acara', '[{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> New\",\"url\":[\"new\"]},{\"label\":\"<i class=\\\"fa fa-suitcase\\\"></i> PM <span id=\\\"menu-badge-1\\\" class=\\\"badge badge-purple\\\" style=\\\"float: right\\\"></span>\",\"url\":[\"pm\"]},{\"label\":\"<i class=\\\"fa fa-inbox\\\"></i> Inbox\",\"url\":[\"inbox\"]},{\"label\":\"<i class=\\\"fa fa-send\\\"></i> Sent\",\"url\":[\"sent\"]},{\"label\":\"<i class=\\\"fa fa-folder-o\\\"></i> Draft\",\"url\":[\"draft\"]}]', '', null, null, null, '2015-08-28 22:06:27', '1');
INSERT INTO `m1000` VALUES ('46', 'sss_po', 'Purchase Order', '[{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> New\",\"url\":[\"new\"]},{\"label\":\"<i class=\\\"fa fa-suitcase\\\"></i> PO List<span id=\\\"menu-badge-1\\\" class=\\\"badge badge-purple\\\" style=\\\"float: right\\\"></span>\",\"url\":[\"list\"]},{\"label\":\"<i class=\\\"fa fa-inbox\\\"></i> Setup\",\"url\":[\"setup\"]}]', null, null, null, null, '2015-08-28 22:06:31', '1');
INSERT INTO `m1000` VALUES ('47', 'sss_report', 'Report', '[{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Dashboard\",\"url\":[\"index\"]},{\"label\":\"<i class=\\\"fa fa-suitcase\\\"></i> Tenant Report<span id=\\\"menu-badge-1\\\" class=\\\"badge badge-purple\\\" style=\\\"float: right\\\"></span>\",\"url\":[\"#\"]},{\"label\":\"<i class=\\\"fa fa-inbox\\\"></i> Member Report\",\"url\":[\"#\"]}]', null, null, null, null, '2015-08-28 22:06:34', '1');
INSERT INTO `m1000` VALUES ('51', 'esm_marketing', 'ESM  Marketing', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Dashboard\",\"url\":[\"/dashboard/esm-marketing\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Chating\",\"url\":[\"/dashboard/esm-marketing/chat\"]}\r\n]', null, null, null, null, '2016-01-16 20:34:45', '1');
INSERT INTO `m1000` VALUES ('52', 'esm_purchasing', 'ESM Purchasing', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Dashboard\",\"url\":[\"/dashboard/esm-purchasing\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Chating\",\"url\":[\"/dashboard/esm-purchasing/chat\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Prodak\",\"url\":[\"/esm/barang\"]},\r\n{\"label\":\"<i class=\\\"fa fa-suitcase\\\"></i> Unit<span id=\\\"menu-badge-1\\\" class=\\\"badge badge-purple\\\" style=\\\"float: right\\\"></span>\",\"url\":[\"/esm/unitbarang\"]},\r\n{\"label\":\"<i class=\\\"fa fa-inbox\\\"></i>Customer\",\"url\":[\"/esm/customer\"]},\r\n{\"label\":\"<i class=\\\"fa fa-inbox\\\"></i>Distributor\",\"url\":[\"/esm/distributor\"]},\r\n{\"label\":\"<i class=\\\"fa fa-inbox\\\"></i>Salesmen\",\"url\":[\"/esm/salesmen\"]}\r\n]', null, null, null, null, '2016-01-16 20:35:14', '1');
INSERT INTO `m1000` VALUES ('53', 'esm_sales', 'ESM Sales', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Dashboard\",\"url\":[\"/dashboard/esm-sales\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Chating\",\"url\":[\"/dashboard/esm-sales/chat\"]}\r\n]', null, null, null, null, '2016-01-16 20:35:22', '1');
INSERT INTO `m1000` VALUES ('54', 'esm_warehouse', 'ESM Warehouse', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Dashboard\",\"url\":[\"/dashboard/esm-warehouse\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Chating\",\"url\":[\"/dashboard/esm-warehouse/chat\"]}\r\n]', null, null, null, null, '2016-01-16 20:35:29', '1');
INSERT INTO `m1000` VALUES ('55', 'esm_factory', 'ESM Factory', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Dashboard\",\"url\":[\"/dashboard/esm-factory\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Chating\",\"url\":[\"/dashboard/esm-factory/chat\"]}\r\n]', null, null, null, null, '2016-01-16 20:35:36', '1');
INSERT INTO `m1000` VALUES ('56', 'esm_datamaster', 'ESM DataMaster', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Dashboard\",\"url\":[\"/dashboard/esm-masterdata\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Chating\",\"url\":[\"/dashboard/esm-masterdata/chat\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> ESM Prodak\",\"url\":[\"/esm/barang\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> ESM Prodak Unit\",\"url\":[\"/esm/unitbarang\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> ESM Disributor\",\"url\":[\"/esm/distributor\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> ESM Customer\",\"url\":[\"/esm/customers\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> ESM Supplier\",\"url\":[\"/esm/supplier\"]}\r\n]', null, null, null, null, '2015-12-04 21:36:44', '1');
INSERT INTO `m1000` VALUES ('57', 'esm_esm', 'ESM Barang', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Dashboard\",\"url\":[\"/dashboard/esm-prodak\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Chating\",\"url\":[\"/dashboard/esm-prodak/chat\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Prodak\",\"url\":[\"/esm/barang\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Distributor\",\"url\":[\"/esm/distributor\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Request Order\",\"url\":[\"/esm/requestorder\"]}\r\n]', null, null, null, null, '2016-01-16 20:35:45', '1');
INSERT INTO `m1000` VALUES ('60', 'alg_marketing', 'ALG Marketing', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Dashboard\",\"url\":[\"/dashboard/alg-marketing\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Chating\",\"url\":[\"/dashboard/alg/marketing-widget/chat\"]}\r\n]', null, null, null, null, '2016-01-16 20:35:51', '1');
INSERT INTO `m1000` VALUES ('61', 'alg_purchasing', 'ALG Purchasing', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Dashboard\",\"url\":[\"/dashboard/alg-purchasing\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Chating\",\"url\":[\"/dashboard/alg-purchasing/chat\"]}\r\n]', null, null, null, null, '2016-01-16 20:35:59', '1');
INSERT INTO `m1000` VALUES ('62', 'alg_sales', 'ALG Sales', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Dashboard\",\"url\":[\"/dashboard/alg-sales\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Chating\",\"url\":[\"/dashboard/alg/sales-chat\"]}\r\n]', null, null, null, null, '2016-01-16 20:36:10', '1');
INSERT INTO `m1000` VALUES ('63', 'alg_warehouse', 'ALG Warehouse', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Dashboard\",\"url\":[\"/dashboard/alg-warehouse\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Chating\",\"url\":[\"/dashboard/alg/warehouse-chat\"]}\r\n]', null, null, null, null, '2016-01-16 20:36:18', '1');
INSERT INTO `m1000` VALUES ('70', 'gsn_marketing', 'GSN Marketing', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Dashboard\",\"url\":[\"/dashboard/gsn-marketing\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Chating\",\"url\":[\"/dashboard/gsn-marketing/chat\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Consumer\",\"url\":[\"/gsn/marketing/konsumen\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Affiliation\",\"url\":[\"/gsn/marketing/afiliasi\"]}\r\n]', null, null, null, null, '2016-01-16 20:36:33', '1');
INSERT INTO `m1000` VALUES ('71', 'gsn_prodak', 'GSN Prodak', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Dashboard\",\"url\":[\"/dashboard/gsn-prodak\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Chating\",\"url\":[\"/dashboard/gsn-prodak/chat\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Product\",\"url\":[\"/gsn/prodak\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Forwarder\",\"url\":[\"/gsn/forwarder\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Kurir\",\"url\":[\"/gsn/kurir\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Consumer\",\"url\":[\"/gsn/konsumen\"]}\r\n]', null, null, null, null, '2016-01-16 20:36:40', '1');
INSERT INTO `m1000` VALUES ('72', 'gsn_afiliasi', 'GSN Affiliasi', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Dashboard\",\"url\":[\"/dashboard/gsn-afiliasi\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Chating\",\"url\":[\"/dashboard/gsn-afiliasi/chat\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Forwarder\",\"url\":[\"/gsn/forwarder\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Kurir\",\"url\":[\"/gsn/kurir\"]}\r\n]', null, null, null, null, '2016-01-16 20:36:49', '1');
INSERT INTO `m1000` VALUES ('73', 'gsn_sales', 'GSN Sales', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Dashboard\",\"url\":[\"/dashboard/gsn-sales\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Chating\",\"url\":[\"/dashboard/gsn-sales/chat\"]}\r\n]', null, null, null, null, '2016-01-16 20:36:57', '1');
INSERT INTO `m1000` VALUES ('74', 'gsn_helpdesk', 'GSN Helpdesk', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Dashboard\",\"url\":[\"/dashboard/gsn-helpdesk\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Chating\",\"url\":[\"/dashboard/gsn-helpdesk/chat\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i>Consumer\",\"url\":[\"/gsn/helpdesk/konsumen\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Affiliation\",\"url\":[\"/gsn/helpdesk/afiliasi\"]}\r\n]', null, null, null, null, '2016-01-16 20:37:05', '1');
INSERT INTO `m1000` VALUES ('75', 'gsn_purchasing', 'GSN Purchasing', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Dashboard\",\"url\":[\"/dashboard/gsn-purchasing\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Chating\",\"url\":[\"/dashboard/gsn-purchasing/chat\"]}\r\n]', null, null, null, null, '2016-01-16 20:37:14', '1');
INSERT INTO `m1000` VALUES ('76', 'gsn_warehouse', 'GSN Warehouse', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Dashboard\",\"url\":[\"/dashboard/gsn-warehouse\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Chating\",\"url\":[\"/dashboard/gsn-warehouse/chat\"]}\r\n]', null, null, null, null, '2016-01-16 20:37:19', '1');
INSERT INTO `m1000` VALUES ('80', 'api_gsn_forwarder', 'Forwarder Gosend', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site/index\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Chating\",\"url\":[\"/widget/chat\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Province\",\"url\":[\"api/gsn/province/index\"]},\r\n{\"label\":\"<i class=\\\"fa fa-suitcase\\\"></i> Department <span id=\\\"menu-badge-1\\\" class=\\\"badge badge-purple\\\" style=\\\"float: right\\\"></span>\",\"url\":[\"/hrd/dept/index\"]},\r\n{\"label\":\"<i class=\\\"fa fa-inbox\\\"></i> Jabatan\",\"url\":[\"/hrd/jabatan/index\"]},\r\n{\"label\":\"<i class=\\\"fa fa-send\\\"></i> Modul\",\"url\":[\"/hrd/modulhrd/index\"]},\r\n{\"label\":\"<i class=\\\"fa fa-send\\\"></i> Modul Setting\",\"url\":[\"/hrd/modulset/index\"]}\r\n]', null, null, null, null, '2015-09-30 21:55:57', '1');
INSERT INTO `m1000` VALUES ('100', 'crm_manufactory', 'CRM manufactory', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Dashboard\",\"url\":[\"/dashboard/crm-manufactory\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Chating\",\"url\":[\"/dashboard/crm-manufactory/chat\"]}\r\n]', null, null, null, null, '2016-01-16 20:37:39', '1');
INSERT INTO `m1000` VALUES ('101', 'crm_distributor', 'CRM distributor', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Dashboard\",\"url\":[\"/dashboard/crm-distributor\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Chating\",\"url\":[\"/dashboard/crm-distributor/chat\"]}\r\n]', null, null, null, null, '2016-01-16 20:37:46', '1');
INSERT INTO `m1000` VALUES ('102', 'crm_outlet', 'CRM outlet', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Dashboard\",\"url\":[\"/dashboard/crm-outlet\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Chating\",\"url\":[\"/dashboard/crm-outlet/chat\"]}\r\n]', null, null, null, null, '2016-01-16 20:37:56', '1');
INSERT INTO `m1000` VALUES ('103', 'crm_salesmen', 'CRM Salesmen', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Dashboard\",\"url\":[\"/dashboard/crm-salesmen\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Chating\",\"url\":[\"/dashboard/crm-salesmen/chat\"]}\r\n]', null, null, null, null, '2016-01-16 20:38:02', '1');
INSERT INTO `m1000` VALUES ('104', 'crm_spg', 'CRM SPG', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i>Dashboard\",\"url\":[\"/dashboard/crm-spg\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Chating\",\"url\":[\"/dashboard/crm-spg/chat\"]},\r\n{\"label\":\"<i class=\\\"fa fa-suitcase\\\"></i>Schadule<span id=\\\"menu-badge-1\\\" class=\\\"badge badge-purple\\\" style=\\\"float: right\\\"></span>\",\"url\":[\"/crm/schadule/spg\"]},\r\n{\"label\":\"<i class=\\\"fa fa-inbox\\\"></i> Entry Data \",\"url\":[\"/crm/sales/spg\"]}\r\n]', null, null, null, null, '2016-01-16 20:38:08', '1');
INSERT INTO `m1000` VALUES ('110', 'itprogrammer', 'dashboard_programmer', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Chating\",\"url\":[\"/widget/chat\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i>Proggres Job\",\"url\":[\"/programmer/proggresjob\"]},\r\n{\"label\":\"<i class=\\\"fa fa-inbox\\\"></i> Org Chart\",\"url\":[\"/programmer/chartorg/index\"]},\r\n{\"label\":\"<i class=\\\"fa fa-inbox\\\"></i> Chart All\",\"url\":[\"/programmer/chart/index\"]},\r\n{\"label\":\"<i class=\\\"fa fa-send\\\"></i> Barcodel\",\"url\":[\"/programmer/qr/index\"]},\r\n{\"label\":\"<i class=\\\"fa fa-send\\\"></i> Signature\",\"url\":[\"/programmer/signature/index\"]},\r\n{\"label\":\"<i class=\\\"fa fa-send\\\"></i> Map\",\"url\":[\"/programmer/map/index\"]},\r\n{\"label\":\"<i class=\\\"fa fa-send\\\"></i> Foursquare\",\"url\":[\"/programmer/foursquare/index\"]},\r\n{\"label\":\"<i class=\\\"fa fa-send\\\"></i> Finger Print\",\"url\":[\"/programmer/finger/index\"]},\r\n{\"label\":\"<i class=\\\"fa fa-send\\\"></i> Cloud Arsip\",\"url\":[\"/programmer/cloud/index\"]}\r\n]', null, null, null, null, '2015-11-21 16:13:24', '1');
INSERT INTO `m1000` VALUES ('111', 'mdefault', 'Default Menu', '[\r\n{\"label\":\"<i class=\\\"fa fa-home\\\"></i> Home \",\"url\":[\"/site/index\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i> Chating\",\"url\":[\"/widget/chat\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i>Help\",\"url\":[\"/widget/help\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i>Tips\",\"url\":[\"/widget/help/doc-tip\"]},\r\n{\"label\":\"<i class=\\\"fa fa-pencil\\\"></i>Database\",\"url\":[\"/widget/help/db-help\"]},\r\n{\"label\":\"<i class=\\\"fa fa-suitcase\\\"></i>Setting <span id=\\\"menu-badge-1\\\" class=\\\"badge badge-purple\\\" style=\\\"float: right\\\"></span>\",\"url\":[\"#\"]}\r\n]', null, null, null, null, '2016-01-22 15:36:26', '1');
